name: templateflutter
description: A new Flutter project.

# Run flutter pub upgrade --major-versions to upgrade all dependencies

publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # L10n
  intl_utils: ^2.8.2
  intl: ^0.17.0

  # State management
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2

  # DI & Routing
  get_it: ^7.2.0
  injectable: ^2.1.1
  auto_route: ^6.0.5

  # Local storage
  hive_flutter: ^1.1.0
  shared_preferences: ^2.1.0

  # UI
  flutter_svg: ^2.0.4
  flash: ^3.0.0
  url_launcher: ^6.1.10
  infinite_scroll_pagination: ^3.2.0
  cached_network_image: ^3.2.3
  blurhash_dart: ^1.2.1
  image: ^4.0.15

  # Network
  dio: ^5.1.1
  json_annotation: ^4.8.0
  retrofit: ^4.0.1

  # Misc
  isolator: ^2.0.3
  dartz: ^0.10.1
  analyzer: ^5.10.0
  package_info: ^2.0.2

  # Firebase
  firebase_core: ^2.9.0
  firebase_analytics: ^10.2.0
  firebase_crashlytics: ^3.1.0
  firebase_remote_config: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generators
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5
  retrofit_generator: ^6.0.0+1
  json_serializable: ^6.6.1
  auto_route_generator: ^6.0.3

  # UI
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.12.0
  device_preview: ^1.1.0

  # Linting
  flutter_lints: ^2.0.1

  # Network
  logger: ^1.3.0

  file: ^6.1.4 #for build_runner

flutter:
  generate: false
  uses-material-design: true
  #  assets:
  #    - assets/images/
  #    - assets/icons/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

flutter_intl: 
  enabled: true
  class_name: S
  main_locale: ru
  arb_dir: lib/app/l10n
  output_dir: lib/app/generated

flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon.png"