name: app_name
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: "3.13.1"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # State management
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2

  # DI & Routing
  get_it: ^7.2.0
  injectable: ^2.1.1
  auto_route: ^7.8.4

  # UI
  flutter_svg: ^2.0.4

  # Utils
  analyzer: ^5.10.0
  package_info_plus: ^5.0.0
  intl: ^0.18.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code generators
  flutter_gen_runner: ^5.3.1
  build_runner: ^2.3.3
  injectable_generator: ^2.1.5
  retrofit_generator: ^8.0.0
  json_serializable: ^6.6.1
  auto_route_generator: ^7.3.2

  # UI
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.1

  # Utils
  flutter_lints: ^2.0.1
  logger: ^2.0.2+1

flutter_gen:
  output: lib/resources/
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      class_name: Assets
  colors:
    enabled: true
    outputs:
      class_name: AppColor
    inputs:
      - assets/colors/colors.xml
  fonts:
    enabled: true
    outputs:
      class_name: AppFont

flutter:
  generate: false
  uses-material-design: true
  #  assets:
  #    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Bold.ttf

flutter_icons:
  android: false
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/icon.png"